/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ir_sahab_regexmatcher_RegexMatcher */

#ifndef _Included_ir_sahab_regexmatcher_RegexMatcher
#define _Included_ir_sahab_regexmatcher_RegexMatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ir_sahab_regexmatcher_RegexMatcher
 * Method:    addPattern
 * Signature: (JJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_ir_sahab_regexmatcher_RegexMatcher_addPattern
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean);

/*
 * Class:     ir_sahab_regexmatcher_RegexMatcher
 * Method:    removePattern
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_sahab_regexmatcher_RegexMatcher_removePattern
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ir_sahab_regexmatcher_RegexMatcher
 * Method:    preparePatterns
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ir_sahab_regexmatcher_RegexMatcher_preparePatterns
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ir_sahab_regexmatcher_RegexMatcher
 * Method:    match
 * Signature: (JLjava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_ir_sahab_regexmatcher_RegexMatcher_match
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ir_sahab_regexmatcher_RegexMatcher
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ir_sahab_regexmatcher_RegexMatcher_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ir_sahab_regexmatcher_RegexMatcher
 * Method:    newInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ir_sahab_regexmatcher_RegexMatcher_newInstance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
